---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#install.packages("jpeg")
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
heartrate<- read.csv("data/heartrate.csv")
```


1. Make a plot that compares the heartrate of patients for drug a.

```{r}
heartrate%>%
  select(patient,a)%>%
  ggplot(aes(x=patient,y=a,fill=patient))+geom_col()+labs(title = "Comparison of Drug A",x=NULL,y="Heartrate")
```


2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate%>%
  pivot_longer(-patient,names_to = "drug",values_to = "heartrate")%>%
  ggplot(aes(x=drug,y=heartrate,fill=drug))+geom_boxplot()+labs(title="Comparison of Heartrate Drugs",x="Drug",y="Heartrate")
```

